apiVersion: batch/v1
kind: Job
metadata:
  name: openBalena-setup
spec:
  template:
    spec:
      containers:
      - name: openBalena-setup
        image: {{ .Values.setup.image }}:{{ .Values.setup.imageVersion }}
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
